import type { AccessRole } from "./types.js";

export const HARD_BLOCKED_COLUMNS = [
  "embedding",
  "password_hash",
] as const;

export const COMMERCE_INTENTS = [
  "get_customer_profile",
  "search_products",
  "get_product_detail",
  "get_order_history",
  "get_order_detail",
  "track_order",
  "get_order_items",
  "initiate_return",
  "get_return_status",
  "get_support_ticket",
  "create_support_ticket",
  "get_loyalty_balance",
  "get_loyalty_history",
  "query_products",
  "query_orders",
  "query_returns",
  "get_return_detail",
  "query_support_tickets",
  "get_loyalty_summary",
  "query_policy_documents",
  "get_policy_document",
  "health_check",
] as const;

type PolicyEntry = {
  allowedIntents: readonly string[];
  allowedColumns: readonly string[];
};

const retailColumns = [
  "id",
  "customer_number",
  "first_name",
  "last_name",
  "full_name",
  "email",
  "phone",
  "address",
  "city",
  "country",
  "loyalty_points",
  "account_status",
  "sku",
  "name",
  "description",
  "category_name",
  "category_slug",
  "price",
  "original_price",
  "stock_quantity",
  "availability_status",
  "warranty_duration",
  "return_window_days",
  "is_promotion_eligible",
  "specifications",
  "order_number",
  "status",
  "delivery_status",
  "tracking_number",
  "total_amount",
  "shipping_address",
  "estimated_delivery_date",
  "actual_delivery_date",
  "quantity",
  "unit_price",
  "subtotal",
  "items",
  "return_number",
  "reason",
  "refund_amount",
  "refund_status",
  "requested_at",
  "resolved_at",
  "ticket_number",
  "subject",
  "priority",
  "assigned_to",
  "queue_position",
  "estimated_wait_minutes",
  "resolution_notes",
  "transaction_type",
  "points",
  "title",
  "content",
  "version",
  "effective_date",
  "policy_key",
  "chunk_index",
  "chunk_text",
  "chunks",
  "created_at",
  "updated_at",
  "service",
];

export const COLUMN_POLICY: Record<AccessRole, PolicyEntry> = {
  customer: {
    allowedIntents: COMMERCE_INTENTS,
    allowedColumns: retailColumns,
  },
  employee: {
    allowedIntents: COMMERCE_INTENTS,
    allowedColumns: retailColumns,
  },
  manager: {
    allowedIntents: COMMERCE_INTENTS,
    allowedColumns: retailColumns,
  },
  hr_officer: {
    allowedIntents: COMMERCE_INTENTS,
    allowedColumns: retailColumns,
  },
  finance_officer: {
    allowedIntents: COMMERCE_INTENTS,
    allowedColumns: retailColumns,
  },
  admin: {
    allowedIntents: COMMERCE_INTENTS,
    allowedColumns: retailColumns,
  },
};
